### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by UserMaxL** [John-Gee/DFC_LM#1]
On the second click it should be "choose" not "chose" I think. Your text is in the future or present and not in the past.

**Comment by John-Gee** [comment]
Thank you for your report, much appreciated!

If you see anything else that is not correct (in content or form), please do tell me and I'll fix it.

**Comment by John-Gee** [comment]
Hey @UserMaxL , seeing that you're my first contributor to issues here and that the project has been funded, I'd like to mark this if you will.

I was thinking of sending some (symbolic) DFI to you, would that be acceptable?
